### ISSUE TITLE
Issues using Mix's versioning

### ISSUE THREAD

**Issue by dniccum** [gmask/MixEEr#1]
I am attempting to use Mix's versioning method to add some cache-busting support, but the plugin is throwing errors after I attempt to execute the version method. Below is what I get:

```
fs.js:653
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/public/dist/css/app.css'
```

I can verify that the file that the error is complaining about has been in fact compiled.

Does this module support the versioning method?

**Comment by gmask** [comment]
It does, and I use it currently on several production systems, can I see your `webpack.mix.js` file as well as your `mix-manifest.json`?

**Comment by dniccum** [comment]
Sure thing, here is my webpack.mix.js:

```javascript
const { mix } = require('laravel-mix');

 mix.sass('resources/scss/app.scss', 'public/dist/css')
    .scripts([
         'resources/js/core.min.js',
         'resources/js/thesaas.js',
         'resources/js/script.js'
    ], 'public/dist/js/app.js')
    .styles([
        'resources/css/core.min.css',
        'resources/css/style.css'
    ], 'public/dist/css/vendor.css')
    .copyDirectory('resources/fonts', 'public/dist/fonts');
```

And here is my mix-manifest.json. This is located within my `/public` directory:

```json
{
    "/dist/js/app.js": "/dist/js/app.js",
    "/dist/css/app.css": "/dist/css/app.css",
    "/dist/css/vendor.css": "/dist/css/vendor.css"
  }
```

**Comment by gmask** [comment]
Ah, so you are receiving that error during compile? e.g., after running `npm run dev` or `npm run watch`.

Which means the issue you're experiencing comes from Laravel Mix itself and not this plugin. I did find the following bug report [#1176](https://github.com/JeffreyWay/laravel-mix/issues/1176), but that only applies to the `hot` script. I was able to duplicate your exact error once during compile but it went away for some unknown reason and I haven't been able to recreate it since. I have some suggestions.

Delete all the mix-manifest files you can find. Add the following to the top of your `webpack.mix.js` file:

```
const { mix } = require('laravel-mix');

mix.options({
    publicPath: 'public',
});

// The rest of your .mix commands go here
```

**Comment by dniccum** [comment]
Worked like a charm, exactly like you described it! Thanks @gmask.
